name: base_setup
description: "_"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  go_router: ^17.0.0
  flutter_animate:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/models/
    - assets/icons/
    - assets/icons/bottom_bar_icons/

  fonts:
    - family: "inter"
      fonts:
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 800
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Thin.ttf
          weight: 200
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 700
